# Generated by Django 5.2.8 on 2025-11-30 18:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Rol',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, unique=True, verbose_name='Perfil de Usuario')),
                ('descripcion', models.TextField(blank=True, null=True, verbose_name='Descripción de las responsabilidades')),
                ('puede_registrar_partos_rn', models.BooleanField(default=False, verbose_name='Permiso: Registrar Partos y RN (HU-02)')),
                ('puede_editar_registros', models.BooleanField(default=False, verbose_name='Permiso: Editar registros clínicos propios (HU-03)')),
                ('puede_ver_datos_clinicos_total', models.BooleanField(default=False, verbose_name='Acceso a todos los registros (Lectura)')),
                ('puede_generar_reportes', models.BooleanField(default=False, verbose_name='Generar reportes ministeriales REM BS22 (HU-04)')),
                ('puede_consultar_auditoria', models.BooleanField(default=False, verbose_name='Consulta de pista de auditoría (HU-05 y HU-10)')),
                ('puede_administrar_usuarios', models.BooleanField(default=False, verbose_name='Administra usuarios (crear/editar/bloquear) (HU-09/11)')),
                ('puede_revisar_logs_tecnicos', models.BooleanField(default=False, verbose_name='Gestiona cuentas y revisa logs técnicos')),
            ],
            options={
                'verbose_name': 'Perfil de Usuario',
                'verbose_name_plural': 'Perfiles de Usuarios',
            },
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre Completo del Trabajador')),
                ('rut', models.CharField(max_length=12, unique=True, verbose_name='RUT (Identificador Único)')),
                ('password', models.CharField(max_length=128, verbose_name='Contraseña (Hasheada Manualmente)')),
                ('is_active', models.BooleanField(default=True, verbose_name='Cuenta Activa/Desbloqueada')),
                ('intentos_fallidos', models.IntegerField(default=0, verbose_name='Intentos fallidos de inicio de sesión')),
                ('token_recuperacion', models.CharField(blank=True, max_length=64, null=True, verbose_name='Token de Recuperación (Opcional)')),
                ('token_expira', models.DateTimeField(blank=True, null=True, verbose_name='Expiración del Token')),
                ('rol', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='login.rol', verbose_name='Rol Asignado')),
            ],
            options={
                'verbose_name': 'Usuario del Sistema',
                'verbose_name_plural': 'Usuarios del Sistema',
            },
        ),
    ]
