# Generated by Django 5.2.6 on 2025-12-05 03:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Madre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('rut', models.CharField(max_length=12, unique=True)),
                ('fecha_nacimiento', models.DateField()),
                ('direccion', models.CharField(blank=True, max_length=255, null=True)),
                ('telefono', models.CharField(blank=True, max_length=20, null=True)),
                ('antecedentes_obstetricos', models.TextField(blank=True, null=True)),
                ('atenciones_clinicas', models.TextField(blank=True, null=True)),
                ('acompañante', models.CharField(blank=True, max_length=255, null=True)),
                ('confirmado', models.BooleanField(default=False)),
            ],
        ),
    ]
