# Generated by Django 5.2.8 on 2025-12-05 16:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('roles', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Madre',
        ),
    ]
