<<<<<<< HEAD
# Generated by Django 5.2.8 on 2025-12-05 16:10
=======
# Generated by Django 5.2.8 on 2025-12-05 16:34
>>>>>>> 7b31e8da05755a72add2ba34f0de0b382edccc02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('roles', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Madre',
        ),
    ]
